# Generated by Django 4.2.11 on 2025-04-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0002_disease_alter_usersymptom_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersymptom',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
