# Generated by Django 4.2.11 on 2025-05-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0003_alter_usersymptom_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersymptom',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='disease',
            name='medicine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='test_results',
            field=models.TextField(blank=True, null=True),
        ),
    ]
