# Generated by Django 4.2.11 on 2025-06-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0004_remove_usersymptom_recommendations_disease_medicine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersymptom',
            old_name='user_id',
            new_name='patient_id',
        ),
    ]
