# Generated by Django 4.2.11 on 2025-07-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_user_patient_email_patient_first_name_and_more'),
        ('symptom_checker', '0005_rename_user_id_usersymptom_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, max_length=100, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('respiratory_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='symptom_checker.disease')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient')),
            ],
        ),
    ]
