# Generated by Django 4.2.11 on 2025-03-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('docter', 'Doctor')], default='user', max_length=50),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
