# Generated by Django 4.2.11 on 2025-05-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='last_visit',
        ),
    ]
